name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_MAIN_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t shivam3127/node-app .
      - name: Publish Image to docker hub
        run: docker push shivam3127/node-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from docker hub
        run: docker pull shivam3127/node-app:latest
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name nodejs-app-container -e MONGO_PASSWORD='${{secrets.MONGO_PASSWORD}}' shivam3127/node-app
